spring:
  profiles:
    active: dev-cmft
  output:
    ansi:
      enabled: detect
  devtools:
    restart:
      exclude: templates
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  mail:
    host: smtp.yeah.net
    username: jerry_chan@yeah.net
    password: cn123456
    default-encoding: utf-8
    senderMail.address: jerry_chan@yeah.net
server:
  port: 8088
  servlet:
    context-path: /sevenup-web-service
mybatis:
  type-aliases-package: com.pofy.chqty.entity
  configuration:
    # 配置项：开启下划线到驼峰的自动转换.
    map-underscore-to-camel-case: true
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  # 枚举类型当成基本类型对待
  enum-as-simple-type: true
  # 配置为 true 后，updateByExample 和 updateByExampleSelective 都必须设置查询条件才能删除，
  # 否则会抛出异常
  safe-update: true