debug: false
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/suwb?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: admin123